#!/bin/bash
if ! type -p ansible-playbook &> /dev/null ; then
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update -y
    sudo apt-get install -y ansible
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ansible-playbook $([ $UID -eq 0 ] || echo -K) -i $HOSTNAME, $DIR/site.yml
