---
- hosts: all
  connection: local
  sudo: yes
  roles:
    - user
    - common
    - cli
    - desktop
    - laptop
    - hostsfile
- hosts: endgames
  connection: local
  sudo: yes
  roles:
    - endgame
