---
- hosts: all
  connection: local
  sudo: yes
  roles:
    - user
    - common
    - cli
    - {role: desktop, when: ansible_env.DISPLAY}
    - {role: laptop, when: ansible_env.DISPLAY}
    - hostsfile
- hosts: endgames
  connection: local
  sudo: yes
  roles:
    - endgame
