---
- hosts: all
  connection: local
  sudo: yes
  roles:
    - user
    - common
    - cli
    - {role: desktop, when: "{{'DISPLAY' in ansible_env}}"}
    - {role: laptop, when: "{{'DISPLAY' in ansible_env}}"}
    - hostsfile
- hosts: endgames
  connection: local
  sudo: yes
  roles:
    - endgame
