- name: Create user
  user:
    name: dschep
    comment: "Daniel Schep"
    group: dschep
    groups: adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare,docker
    append: yes
    update_password: on_create
    password: "$6$JWe9jC8eZs$D.GtnsqSFp09lOFLUfKdCO6eTZ/SbB6dilHCst5SlnYCMzUyQAO/EQYsse1XqwspTDIvtXmTWGcI2N89I0jid/"
