- name: Install Browsers (from Ubuntu)
  apt: pkg={{ item }}
  with_items:
    - iceweasel
    - chromium

- name: Install Flash
  apt: pkg={{ item }}
  with_items:
    - flashplugin-nonfree
    - pepperflashplugin-nonfree
- name: Get Pepper Flash status (for Chromium)
  shell: '[ "$(update-pepperflashplugin-nonfree --status|cut -d: -f2|uniq|wc -l)" -eq 1 ]'
  register: pepper_flash_status
  ignore_errors: True
  changed_when: False
- name: Update Pepper Flash Plugin (for Chromium)
  command: update-pepperflashplugin-nonfree --install
  when: pepper_flash_status|failed

- include: mozilla.yml ff_dl_product=firefox-latest ff_dest=/opt/firefox ff_link_name=firefox
- include: mozilla.yml ff_dl_product=firefox-aurora-latest ff_dest=/opt/firefox-de ff_link_name=firefox-developer-edition

- name: set default browser (firefox-mozilla)
  alternatives: name=x-www-browser path=/usr/bin/firefox


#- name: media repo (FF h.264 support)
#  apt_repository: repo='ppa:mc4man/trusty-media'
#
#- name: Install ff h.264 support
#  apt: pkg={{ item }}
#  with_items    - gstreamer0.10-ffmpeg
#    - ubuntu-restricted-extras
