- name: Install Desktop Environment
  apt: pkg={{ item }}
  with_items:
    - lubuntu-desktop
    - awesome
    - gnome-terminal
    - xfce4-volumed
    - xfce4-mixer
    - gstreamer0.10-alsa
    - ssh-askpass-gnome
