- name: set zenburn colors (gnome-terminal)
  sudo: no
  gconftool-2: key={{  item.key }} string={{ item.string|default(omit) }} bool={{ item.bool|default(omit) }}
  with_items:
    - key: /apps/gnome-terminal/profiles/Default/palette
      string: "#3F3F3F3F3F3F:#CCCC93939393:#7F7F9F9F7F7F:#E3E3CECEABAB:#DFDFAFAF8F8F:#CCCC93939393:#8C8CD0D0D3D3:#DCDCDCDCCCCC:#3F3F3F3F3F3F:#CCCC93939393:#7F7F9F9F7F7F:#E3E3CECEABAB:#DFDFAFAF8F8F:#CCCC93939393:#8C8CD0D0D3D3:#DCDCDCDCCCCC"
    - key: /apps/gnome-terminal/profiles/Default/background_color
      string: "#3F3F3F3F3F3F"
    - key: /apps/gnome-terminal/profiles/Default/foreground_color
      string: "#DCDCDCDCCCCC"
    - key: /apps/gnome-terminal/profiles/Default/bold_color
      string: "#E3E3CECEABAB"
    - key: /apps/gnome-terminal/profiles/Default/bold_color_same_as_fg
      bool: false
    - key: /apps/gnome-terminal/profiles/Default/use_theme_colors
      bool: false

- name: set hotkeys (gnome-terminal)
  sudo: no
  gconftool-2: key={{  item.key }} string={{ item.string|default(omit) }} bool={{ item.bool|default(omit) }}
  with_items:
    - key: /apps/gnome-terminal/keybindings/next_tab
      string: "<Ctrl><Shift>k"
    - key: /apps/gnome-terminal/keybindings/prev_tab
      string: "<Ctrl><Shift>j"

- name: use Hack (gnome-terminal)
  sudo: no
  gconftool-2: key={{  item.key }} string="{{ item.string|default(omit) }}" bool={{ item.bool|default(omit) }}
  with_items:
    - key: /apps/gnome-terminal/profiles/Default/use_system_font
      bool: false
    - key: /apps/gnome-terminal/profiles/Default/font
      string: 'Hack 10'

- name: hide menubar by default (gnome-terminal)
  sudo: no
  gconftool-2: key=/apps/gnome-terminal/profiles/Default/default_show_menubar bool=false
