- name: set zenburn color scheme
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/palette
    string: "#3F3F3F3F3F3F:#CCCC93939393:#7F7F9F9F7F7F:#E3E3CECEABAB:#DFDFAFAF8F8F:#CCCC93939393:#8C8CD0D0D3D3:#DCDCDCDCCCCC:#3F3F3F3F3F3F:#CCCC93939393:#7F7F9F9F7F7F:#E3E3CECEABAB:#DFDFAFAF8F8F:#CCCC93939393:#8C8CD0D0D3D3:#DCDCDCDCCCCC"

- name: set highlighted color to be different from foreground-color
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/bold_color_same_as_fg
    bool: false

- name: set background color
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/background_color
    string: "#3F3F3F3F3F3F"
- name: set foreground color
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/foreground_color
    string: "#DCDCDCDCCCCC"
- name: set highlight color
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/bold_color
    string: "#E3E3CECEABAB"

- name: make sure the profile is set to not use theme colors
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/use_theme_colors
    bool: false

- name: don't use system font 
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/use_system_font
    bool: false
- name: set font to source code pro
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/font
    string: "Source Code Pro 10"

- name: hide menubar by default
  sudo: no
  gconftool-2:
    key: /apps/gnome-terminal/profiles/Default/default_show_menubar
    bool: false
