- name: Install Password Manager
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - keepassx

- name: Install Various CLI/GUI Tools
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - xclip
    - imagemagick

- name: Install GUI Tools
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - parcellite
