- name: Install Password Manager
  apt: pkg={{ item }}
  with_items:
    - keepassx

- name: Install Various CLI/GUI Tools
  apt: pkg={{ item }}
  with_items:
    - xclip
    - imagemagick

- name: Install GUI Tools
  apt: pkg={{ item }}
  with_items:
    - gimp
    - gnome-mplayer
    - ubuntu-restricted-extras
    - skype
    - gajim

- name: install imgur screenshot script
  get_url: url=https://raw.githubusercontent.com/dschep/img/master/img.sh dest=/usr/bin/img.sh mode=755
