- name: Install Password Manager
  apt: pkg={{ item }}
  with_items:
    - keepassx

- name: Install Various CLI/GUI Tools
  apt: pkg={{ item }}
  with_items:
    - xclip
    - imagemagick

- name: Install GUI Tools
  apt: pkg={{ item }}
  with_items:
    - parcellite
    - gimp
    - gnome-mplayer
    - skype
