- name: Make /etc/hosts.d
  file: path=/etc/hosts.d state=directory
  register: made_hosts_d
- name: Move default host file
  copy: src=/etc/hosts dest=/etc/hosts.d/default
  when: made_hosts_d|changed

- include: 'adblock.yml'

- name: Combine host files
  assemble: src=/etc/hosts.d dest=/etc/hosts backup=yes mode=644
