#!/bin/bash

if [ "$1" == '--notify-done' ] ; then
    start=$(date +%s)

    "${@:2}"

    ret=$( [ $? -eq 0 ] && echo succeeded || echo failed )
    end=$(date +%s)

    durat=$(echo "($end - $start) / 60" | bc)

    msg="'${*:2}' $ret in $durat min"
else
    msg="$*"
fi

curl -s https://api.pushover.net/1/messages.json \
    -d token=$PUSHOVER_APP_TOKEN \
    -d user=$PUSHOVER_USER_TOKEN \
    -d title=$USER@$HOSTNAME \
    -d message="$msg" > /dev/null
