- name: Make /etc/hosts.d
  file: path=/etc/hosts.d state=directory
  register: made_hosts_d
- name: Move default host file
  copy: src=/etc/hosts dest=/etc/hosts.d/default
  when: made_hosts_d|changed
- name: Download someonewhocares' hostfile
  get_url: url=http://someonewhocares.org/hosts/hosts dest=/etc/hosts.d/someonewhocares force=yes
- name: Combine host files
  assemble: src=/etc/hosts.d dest=/etc/hosts backup=yes mode=644
