- name: Setup power.d cpufreq hook
  copy: src=cpufreq dest=/etc/pm/power.d/cpufreq mode=755

- name: Setup power.d brightness hook
  copy: src=brightness dest=/etc/pm/power.d/brightness mode=755

# NOTE: we're assuming / is on sda
- name: Check if sda is an SSD
  shell: 'grep 0 /sys/block/sda/queue/rotational'
  register: ssd
  ignore_errors: True
  changed_when: False
# NOTE: the regex only fails to match if discard is the first option
- name: Set discard on /
  lineinfile: dest=/etc/fstab backup=yes backrefs=yes regexp='[^#](\S+\s+/\s+\S+\s+)((?!discard)\S+)(.*)' line='\1discard,\2'
  when: ssd|success

- name: Check if X1 Carbon v2
  shell: 'dmidecode | grep "Version: ThinkPad X1 Carbon 2nd"'
  register: x1_carbon_v2
  ignore_errors: True
  changed_when: False
- name: Set default sound card
  lineinfile: dest=/etc/asound.conf create=yes line='{{ item }}'
  when: x1_carbon_v2|success
  with_items:
    - defaults.ctl.card 1
    - defaults.pcm.card 1
    - defaults.timer.card 1

- name: Install laptop packages
  apt: pkg={{ item }}
  with_items:
    - acpi
    - powertop

- name: Install VPN frontend
  apt: pkg={{ item }}
  with_items:
    - network-manager-openvpn
    - network-manager-openvpn-gnome
