- name: hipchat repo
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main'
- name: hipchat signing key
  apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present
  register: hipchat_key
- name: update package cache
  apt: update_cache=yes
  when: hipchat_key|changed

- name: install email, chat & vpn
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - evolution
    - evolution-ews
    - hipchat
    - network-manager-openconnect-gnome
    - openconnect

- name: change avahi domain
  lineinfile: dest=/etc/avahi/avahi-daemon.conf line="domain-name=avahi" insertafter="#domain-name"
- name: change DNS resolution order to work with openconnect
  lineinfile: "dest=/etc/avahi/avahi-daemon.conf line='hosts: files dns mdns4_minimal' regexp='^hosts:\\s*files\\s+mdns.*$'"

- name: disable error reporting
  service: name={{ item }} enabled=no state=stopped
  with_items:
      - apport
      - whoopsie
