- name: Configure Apt for Debian Sid
  copy: src=sources.list dest=/etc/apt/sources.list

- name: Install apt_repository dep and HTTPS transport
  apt: pkg={{ item }}
  with_items:
    - python-pycurl
    - apt-transport-https

- name: Update package cache
  apt: update_cache=yes

- name: Upgrade all packages
  apt: upgrade=dist
