- name: Add Git PPA
  apt_repository: repo='ppa:git-core/ppa'

- name: Install CLI Editors/Seach/VCS/Diff Tools
  apt: pkg={{ item }}
  with_items:
    - vim
    - ack-grep
    - silversearcher-ag
    - git
    - jq
    - ngrok-client

- name: Install Python Tools
  apt: pkg={{ item }}
  with_items:
    - python-virtualenv
    - virtualenvwrapper
    - python-pip
    - python-dev

- name: Pip Install Python Tools
  pip: name={{ item }}
  with_items:
    - fabric
    - pex
    - httpie

- name: Install Android Tools
  apt: pkg={{ item }}
  with_items:
    - android-tools-adb
    - android-tools-fastboot

- name: Install common build deps
  apt: pkg={{ item }}
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - libjpeg-dev
