#- name: Add Git PPA
#  apt_repository: repo='ppa:git-core/ppa'
#
#- name: Add Git PPA
#  apt_repository: repo='ppa:neovim-ppa/unstable'

- name: Install CLI Editors/Seach/VCS/Diff Tools
  apt: pkg={{ item }}
  with_items:
    #- neovim
    - vim
    - ack-grep
    - silversearcher-ag
    - git
    - httpie
    - jq
    - ngrok-client

- name: Install Python Tools
  apt: pkg={{ item }}
  with_items:
    - python-virtualenv
    - virtualenvwrapper
    - python-pip
    - python-dev

- name: Pip Install Python Tools
  pip: name={{ item }}
  with_items:
    - fabric
    - pex
    - httpie
    - neovim

- name: Install Android Tools
  apt: pkg={{ item }}
  with_items:
    - android-tools-adb
    - android-tools-fastboot

- name: Install common build deps
  apt: pkg={{ item }}
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - libjpeg-dev
