- name: Install CLI Editors/Seach/VCS/Diff Tools
  apt: pkg={{ item }}
  with_items:
    - vim
    - ack-grep
    - silversearcher-ag
    - git

- name: Install Python Tools
  apt: pkg={{ item }}
  with_items:
    - python-virtualenv
