- name: dotfiles
  sudo_user: dschep
  copy: src=dotfiles/{{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - bash_profile
    - bash_logout
    - liquidprompt/
    - vimrc
    - gitignore
    - gitconfig
    - inputrc

- name: Create Neovim config directory
  sudo_user: dschep
  file: path=/home/dschep/.config/nvim state=directory

- name: Symlink NeoVim configuration
  sudo_user: dschep
  file: src="/home/dschep/.vimrc" dest=/home/dschep/.config/nvim/init.vim state=link

