- name: dotfiles
  sudo: no
  copy: src=dotfiles/{{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - bash_profile
    - bash_logout
    - liquidprompt/
    - vimrc
    - gitignore
    - gitconfig
    - inputrc
