- name: Install Various CLI Tools
  apt: pkg={{ item }}
  with_items:
    - dos2unix
    - inotify-tools
    - unrar
    - p7zip-full
    - dtrx
    - htop
    - sshuttle
    - ethtool
    - nmap

- name: Install encfs
  apt: pkg={{ item }}
  with_items:
    - encfs
