- name: Install Various CLI Tools
  apt: pkg={{ item }}
  with_items:
    # basic file tools
    - dos2unix
    - inotify-tools
    # compression tools
    - unrar
    - p7zip-full
    - dtrx
    # system tools
    - htop
    - apt-file
    # network
    - ethtool
    - nmap
    # disc encryption
    - encfs
