- name: Install Various CLI Tools
  apt: pkg={{ item }}
  with_items:
    # basic file tools
    - dos2unix
    - inotify-tools
    # compression tools
    - unrar-free
    - p7zip-full
    - dtrx
    # system tools
    - htop
    - apt-file
    # network
    - ethtool
    # disc encryption
    - encfs
- name: Install Various CLI netsec Tools
  apt: pkg={{ item }}
  with_items:
    - nmap
    - libssl-dev
    - libffi-dev
    - dsniff

- name: install custom pushover util
  copy: src=pushover/pushover dest=/usr/bin/pushover mode=755

- name: install document creation tools (pandoc & pdflatex & fonts)
  apt: pkg={{ item }}
  with_items:
    - pandoc
    - texlive
